### ISSUE TITLE
Throwing shuriken crashes server

### ISSUE THREAD

**Issue by deviantfero** [python-bear/tead-1.20.1#2]
fabric server crashes when throwing a shuriken, also arrows don't seem to have any effect.

fabric 1.20.4

let me know if you need any more details.

also I noticed there's no support for 1.20.4 on this page, but modrinth has a 0.4 release there. Are you officially supporting 1.20.4?

**Comment by python-bear** [comment]
Does the server crash give you any error messages? I'm new to making mods so I might need the help.

About the arrows, you need to use them with the trick bow, are you doing that? If you are then I probably made a mistake in the code and I'll add it to my list of things to change.
Thanks for your help!

— P̲ythonBear 🐍🐻

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by deviantfero** [comment]
```
java.lang.ExceptionInInitializerError: null
	at net.pythonbear.tead.item.ShurikenItem.method_7836(ShurikenItem.java:28) ~[tead-0.4-1.20.4.jar:?]
	at net.minecraft.class_1799.method_7913(class_1799.java:312) ~[server-intermediary.jar:?]
	at net.minecraft.class_3225.method_14256(class_3225.java:295) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12065(class_3244.java:1171) ~[server-intermediary.jar:?]
	at net.minecraft.class_2886.method_12550(class_2886.java:29) ~[server-intermediary.jar:?]
	at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:757) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: This registry can't create intrusive holders
	at net.minecraft.class_2370.method_40269(class_2370.java:371) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.<init>(class_1299.java:169) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299$class_1300.method_5905(class_1299.java:775) ~[server-intermediary.jar:?]
	at net.fabricmc.fabric.api.object.builder.v1.entity.FabricEntityTypeBuilder.build(FabricEntityTypeBuilder.java:342) ~[fabric-object-builder-api-v1-13.0+dba1195c4f-da2eae14e6394a9.jar:?]
	at net.pythonbear.tead.entity.TeadEntities.<clinit>(TeadEntities.java:16) ~[tead-0.4-1.20.4.jar:?]
	... 20 more
```

this is the exception I get, I have the mod installed in client and server

And about the bow, no I wasnt using the trick bow, thanks for the tip

**Comment by python-bear** [comment]
Thanks, I'll look into when I get the time.

— P̲ythonBear 🐍🐻

Sent from Proton Mail mobile

-------- Original Message --------
