### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by jacklollz2** [python-bear/tead-1.20.1#4]
The contents of this have been erased.

**Comment by python-bear** [comment]
😭 what. IDK bro, I'll get to it in a couple weeks unless you really want me to try and fix it now.

**Comment by jacklollz2** [comment]
I don't know either, any time anyone equips copper armor results in an instant crash for their client

**Comment by jacklollz2** [comment]
Removing shaders, Iris, visuality, etc. still results in the same crash:
```
Description: Rendering entity in world

net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: textures/models/armor/tead:copper_layer_1.png
	at net.minecraft.class_2960.method_45135(class_2960.java:232)
	at net.minecraft.class_2960.<init>(class_2960.java:47)
	at net.minecraft.class_2960.<init>(class_2960.java:51)
	at net.minecraft.class_2960.<init>(class_2960.java:56)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
	at net.minecraft.class_970.handler$bbc000$chime$getArmorTexture(class_970.java:2553)
	at net.minecraft.class_970.method_4174(class_970.java)
	at net.minecraft.class_970.method_23192(class_970.java:118)
	at net.minecraft.class_970.method_4169(class_970.java:75)
	at net.minecraft.class_970.method_17157(class_970.java:45)
	at net.minecraft.class_970.method_4199(class_970.java:27)
	at net.minecraft.class_922.redirect$lbi000$apoli$preventFeatureRendering(class_922.java:7068)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:66)
	at net.minecraft.class_1007.method_3936(class_1007.java:43)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by jacklollz2** [comment]
Problem isn't exclusive to copper armor, any armor from tead causes it. Gold:
```
Description: Rendering entity in world

net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: textures/models/armor/tead:gold_stalwart_layer_1.png
	at net.minecraft.class_2960.method_45135(class_2960.java:232)
	at net.minecraft.class_2960.<init>(class_2960.java:47)
	at net.minecraft.class_2960.<init>(class_2960.java:51)
	at net.minecraft.class_2960.<init>(class_2960.java:56)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
	at net.minecraft.class_970.handler$bbc000$chime$getArmorTexture(class_970.java:2553)
	at net.minecraft.class_970.method_4174(class_970.java)
	at net.minecraft.class_970.method_23192(class_970.java:118)
	at net.minecraft.class_970.method_4169(class_970.java:75)
	at net.minecraft.class_970.method_17157(class_970.java:42)
	at net.minecraft.class_970.method_4199(class_970.java:27)
	at net.minecraft.class_922.redirect$lbi000$apoli$preventFeatureRendering(class_922.java:7068)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:66)
	at net.minecraft.class_1007.method_3936(class_1007.java:43)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_490.method_29977(class_490.java:151)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1191)
	at net.minecraft.class_490.method_48472(class_490.java:151)
	at net.minecraft.class_490.method_2486(class_490.java:128)
	at net.minecraft.class_481.method_2389(class_481.java:794)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:722)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by python-bear** [comment]
I'm not gonna lie, the code is a mess and I'm still on the process of fixing it, I'll try and get to it as soon as possible though.

**Comment by python-bear** [comment]
Okay, I've completely remade all of the armor and I'll try and recreate the issue.
